
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzivxwkzjkarxnviqgbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6aXZ4d2t6amthcnhudmlxZ2J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTY2MjIsImV4cCI6MjA2MzQ5MjYyMn0.HBrfimAVbGCJ8UlrBIK27euvX8QM_tabJTuY1FFpeNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
